# Generated by Django 2.1.2 on 2019-01-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descricao do produto ou servico', max_length=120, verbose_name='Descricao')),
                ('unidade', models.CharField(blank=True, help_text='Unidade Comercial', max_length=6, null=True, verbose_name='Unidade')),
            ],
        ),
    ]
