# Generated by Django 2.1.5 on 2019-01-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_interno',
            field=models.PositiveIntegerField(default=0, verbose_name='Código Interno'),
        ),
    ]
