# Generated by Django 2.1.5 on 2019-01-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produto_cod_interno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='cod_interno',
            new_name='codigo',
        ),
    ]
