# Generated by Django 2.1.5 on 2019-01-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190112_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default=0, max_length=60, verbose_name='Código Interno'),
        ),
    ]
