version: '3'

services:
  # Database
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: dashboard
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
    restart: always
    ports:
      - 8082:80
    volumes:
      - /sessions

  #Backend Django
  backend:
    user: 1000:1000
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./log:/log
      - ./archive:/archive
    depends_on:
      - database
    ports:
      - 8081:8081

  # # Frontend
  # frontend:
  #   user: 1000:1000
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app/
  #   env_file:
  #     - .env

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./frontend/build:/var/www/frontend
      - ./nginx/conf.d:/etc/nginx/conf.d/default.conf:ro
      - ./log:/log
    depends_on:
      - backend
      # - frontend

