# Generated by Django 2.1.2 on 2019-01-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('inscricao_estatual', models.CharField(max_length=14, verbose_name='Inscricao Estadual')),
                ('nome', models.CharField(max_length=60, verbose_name='Razao Social ou Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome fantasia')),
                ('bairro', models.CharField(max_length=60, verbose_name='Bairro')),
                ('logradouro', models.CharField(max_length=60, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=60, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone')),
                ('crt', models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional, excesso sublimite de receita bruta'), ('3', 'Regime Normal')], max_length=1, verbose_name='Código de Regime Tributário')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.City', verbose_name='Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.State', verbose_name='Estado')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Country', verbose_name='Pais')),
            ],
        ),
    ]
