# Generated by Django 2.1.1 on 2018-10-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('social_name', models.CharField(max_length=1024, verbose_name='Social Name')),
                ('adress', models.CharField(max_length=1024, verbose_name='Adress')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.City', verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Country', verbose_name='Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.State', verbose_name='State')),
            ],
        ),
    ]
