# Generated by Django 2.1.1 on 2018-10-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Store', verbose_name='Store')),
            ],
        ),
    ]
