# Generated by Django 2.1.2 on 2018-10-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20181019_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Number'),
        ),
    ]
