# Generated by Django 2.1.2 on 2019-01-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.CharField(choices=[('55', '55 - NF-e'), ('65', '65 - NFC-e')], help_text='Código do Modelo', max_length=2, verbose_name='Modelo')),
                ('serie', models.CharField(help_text='Série do Documento Fiscal', max_length=3, verbose_name='S')),
                ('numero', models.CharField(help_text='Número do Documento Fiscal', max_length=9, verbose_name='Número')),
                ('data', models.DateField(help_text='Data e hora de emissão do Documento Fiscal', verbose_name='Data Emissão')),
                ('tp_operacao', models.CharField(choices=[('0', '0 - Entrada'), ('1', '1 - Saída')], help_text='Tipo de Operação', max_length=1, verbose_name='Operação')),
                ('id_destino', models.CharField(choices=[('1', '1 - Operação interna'), ('2', '2 - Operação interestadual'), ('3', '3 - Operação com exterior')], help_text='Identificador de local de destino da operação', max_length=1, verbose_name='Destino')),
                ('tp_emissao', models.CharField(choices=[('1', '1-Emissão normal'), ('2', '2-Contingência FS-IA'), ('3', '3-Contingência SCAN'), ('4', '4-Contingência DPEC'), ('5', '5-Contingência FS-DA'), ('6', '6-Contingência SVC-AN'), ('7', '7-Contingência SVC-RS'), ('9', '7-Contingência off-line da NFC-e')], help_text='Tipo de Emissão da NF-e', max_length=1, verbose_name='Tipo de Emissão')),
                ('chave_acesso', models.CharField(help_text='Código Numérico que compõe a Chave de Acesso', max_length=8, verbose_name='Chave de Acesso')),
                ('chave_acesso_dv', models.CharField(help_text='Dígito Verificador da Chave de Acesso da NF-e', max_length=1, verbose_name='DV Chave de Acesso')),
                ('n_item', models.PositiveIntegerField(default=0, help_text='Quantidade de Items', verbose_name='Items')),
                ('v_total', models.DecimalField(decimal_places=3, default=0, help_text='Valor Total da NF-e', max_digits=15, verbose_name='Valor Total')),
                ('v_total_tributo', models.DecimalField(decimal_places=3, default=0, help_text='Valor aproximado total de tributos federais, estaduais e municipais.', max_digits=15, verbose_name='Total de Tributos')),
                ('v_total_desconto', models.DecimalField(decimal_places=3, default=0, help_text='Valor Total do Desconto', max_digits=15, verbose_name='Total de Descontos')),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Loja', verbose_name='Emitente')),
            ],
        ),
    ]
