# Generated by Django 2.1.1 on 2018-10-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=128, verbose_name='Option')),
                ('value', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Value')),
                ('date_time', models.DateTimeField(verbose_name='Date Time')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Canceled')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Amount')),
                ('discount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Discount')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Canceled')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Checkout', verbose_name='Checkout')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Store', verbose_name='Store')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Ticket', verbose_name='Ticket'),
        ),
    ]
