# Generated by Django 2.1.2 on 2019-01-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='data',
            field=models.DateTimeField(help_text='Data e hora de emissão do Documento Fiscal', verbose_name='Data Emissão'),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='serie',
            field=models.CharField(help_text='Série do Documento Fiscal', max_length=3, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='tp_emissao',
            field=models.CharField(choices=[('1', '1 - Emissão normal'), ('2', '2 - Contingência FS-IA'), ('3', '3 - Contingência SCAN'), ('4', '4 - Contingência DPEC'), ('5', '5 - Contingência FS-DA'), ('6', '6 - Contingência SVC-AN'), ('7', '7 - Contingência SVC-RS'), ('9', '7 - Contingência off-line da NFC-e')], help_text='Tipo de Emissão da NF-e', max_length=1, verbose_name='Tipo de Emissão'),
        ),
    ]
