# Generated by Django 2.1.2 on 2018-10-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='discount_percentage',
            field=models.FloatField(null=True, verbose_name='Discount Percentage'),
        ),
    ]
