# Generated by Django 2.1.2 on 2018-10-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_ticket_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Discount'),
        ),
    ]
