# Generated by Django 2.1.2 on 2019-01-10 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('sale', '0002_auto_20190106_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(blank=True, help_text='GTIN (Global Trade Item Number) do produto', max_length=14, null=True, verbose_name='EAN')),
                ('descricao', models.CharField(help_text='Descrição do produto', max_length=120, verbose_name='Descrição')),
                ('ncm', models.CharField(default='00', help_text='Código NCM', max_length=8, verbose_name='NCM')),
                ('cfop', models.CharField(help_text='Código Fiscal de Operações e Prestações', max_length=4, verbose_name='CFOP')),
                ('unidade', models.CharField(help_text='Unidade Comercial', max_length=6, verbose_name='Unidade')),
                ('quantidade', models.FloatField(default=0, help_text='Quantidade Comercial', verbose_name='Quantidade')),
                ('v_bruto_total', models.FloatField(default=0, help_text='Valor Total Bruto dos Produtos', verbose_name='Total Bruto')),
                ('u_tributavel', models.CharField(blank=True, max_length=6, null=True, verbose_name='Unidade Tributável')),
                ('q_tributavel', models.FloatField(default=0, verbose_name='Quantidade Tributável')),
                ('v_unitario', models.FloatField(default=0, help_text='Valor Unitário de tributação', verbose_name='Tributação')),
                ('flag_total', models.CharField(choices=[('0', '0 - Valor do item não compõe o valor total da NF-e'), ('1', '1 - Valor do item compõe o valor total da NF-e')], help_text='Indica se valor do Item entra no valor total da NF-e', max_length=1, verbose_name='Modelo')),
            ],
        ),
        migrations.AlterField(
            model_name='nfe',
            name='v_total_desconto',
            field=models.FloatField(default=0, help_text='Valor Total do Desconto', verbose_name='Total de Descontos'),
        ),
        migrations.AlterField(
            model_name='nfe',
            name='v_total_tributo',
            field=models.FloatField(default=0, help_text='Valor aproximado total de tributos federais, estaduais e municipais.', verbose_name='Total de Tributos'),
        ),
        migrations.AddField(
            model_name='nfproduto',
            name='nf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Nfe', verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='nfproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Produto', verbose_name='Produto'),
        ),
    ]
