# Generated by Django 2.1.2 on 2019-01-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20190110_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfproduto',
            name='v_unit_tributacao',
            field=models.FloatField(default=0, help_text='Valor Unitário de tributação', verbose_name='Tributação'),
        ),
        migrations.AlterField(
            model_name='nfproduto',
            name='v_unitario',
            field=models.FloatField(default=0, help_text='Valor Unitário de Comercialização', verbose_name='Valor Unitário'),
        ),
    ]
