# Generated by Django 2.1.2 on 2019-01-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20190110_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_pagamento', models.CharField(choices=[('01', '01 - Dinheiro'), ('02', '02 - Cheque'), ('03', '03 - Cartão de Crédito'), ('04', '04 - Cartão de Débito'), ('05', '05 - Crédito Loja'), ('10', '10 - Vale Alimentação'), ('11', '11 - Vale Refeição'), ('12', '12 - Vale Presente'), ('13', '13 - Vale Combustível'), ('99', '99 - Outros')], max_length=2, verbose_name='Forma de pagamento')),
                ('valor', models.FloatField(default=0, verbose_name='Valor do Pagamento')),
                ('nf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Nfe', verbose_name='Nota Fiscal')),
            ],
        ),
    ]
