# Generated by Django 2.1.2 on 2019-01-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_nfpagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfpagamento',
            old_name='t_pagamento',
            new_name='f_pagamento',
        ),
    ]
