# Generated by Django 2.1.5 on 2019-01-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20190112_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfe',
            old_name='n_item',
            new_name='q_item',
        ),
    ]
