# Generated by Django 2.1.5 on 2019-01-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20190112_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfproduto',
            name='n_item',
            field=models.PositiveIntegerField(default=1, help_text='Número do item', verbose_name='Número'),
        ),
    ]
