# Generated by Django 2.1.5 on 2019-01-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_nfproduto_n_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfproduto',
            name='v_total_tributo',
            field=models.FloatField(default=0, help_text='Valor aproximado total de tributos federais, estaduais e municipais.', verbose_name='Total de Tributos'),
        ),
    ]
