# Generated by Django 2.1.1 on 2018-10-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('uf', models.CharField(max_length=5, verbose_name='UF')),
                ('contry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Country', verbose_name='Contry')),
            ],
        ),
    ]
